services:
  - type: web
    name: bidmont-api
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bidmont-db
          property: connectionString

databases:
  - name: bidmont-db
    databaseName: bidmont
    user: bidmont
    plan: free
