"""Unit tests for the site's Montenegrin/English localization data.

build.py bakes ~450 data-i18n / data-i18n-attr / data-i18n-html keys across
the 8 generated pages; assets/js/i18n.js's I18N dict is the only source of
"en" text for all of them (Montenegrin is already baked into the HTML, so a
missing "me" entry only breaks the English->Montenegrin round trip, but a
missing "en" entry breaks the visible page the moment someone toggles
language - both are worth catching before they ship, not after).

These tests don't run the site - they statically cross-check the two
artifacts (generated HTML + the JS dict) agree on every key, which is the
one property a typo or a forgotten translation would silently violate.
"""
import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
PAGES = ["index.html", "credits.html", "auctions.html", "auth.html",
         "auction.html", "account.html", "support.html", "admin.html"]


def _load_i18n_dict():
    """assets/js/i18n.js embeds `var I18N = {...};` as a strictly JSON-valid
    object literal (see the file's own header comment) specifically so this
    can be sliced out and json.loads()'d instead of parsed as JS."""
    src = (REPO_ROOT / "assets" / "js" / "i18n.js").read_text(encoding="utf-8")
    m = re.search(r"var I18N = (\{.*?\});\n", src, re.S)
    assert m, "assets/js/i18n.js: couldn't find `var I18N = {...};`"
    return json.loads(m.group(1))


def _keys_used_in_html():
    """Every data-i18n[-attr|-html]="key" referenced across the generated
    pages. Pages must already be built (they're committed artifacts - see
    build.py's own output loop - not generated by the test suite)."""
    keys = set()
    for fn in PAGES:
        path = REPO_ROOT / fn
        assert path.exists(), f"{fn} missing at repo root - run `python build.py`"
        html = path.read_text(encoding="utf-8")
        keys.update(re.findall(r'data-i18n="([a-zA-Z0-9_]+)"', html))
        keys.update(re.findall(r'data-i18n-html="([a-zA-Z0-9_]+)"', html))
        keys.update(re.findall(r'data-i18n-attr="[a-zA-Z-]+:([a-zA-Z0-9_]+)"', html))
    return keys


def test_i18n_dict_is_valid_json():
    d = _load_i18n_dict()
    assert len(d) > 100  # sanity: not an empty/truncated slice


def test_every_html_i18n_key_has_both_languages():
    i18n = _load_i18n_dict()
    used = _keys_used_in_html()
    missing = used - set(i18n)
    assert not missing, f"keys used in HTML but absent from i18n.js: {sorted(missing)}"
    incomplete = {k for k in used if not (i18n[k].get("me") and i18n[k].get("en"))}
    assert not incomplete, f"keys missing me/en text: {sorted(incomplete)}"


@pytest.mark.parametrize("key", ["logging_in", "hide_password", "ended"])
def test_js_only_dynamic_keys_present(key):
    """assets/js/main.js calls t() with these at runtime (password show/hide
    toggle, login-in-progress button text, expired countdown) - they never
    appear as a data-i18n attribute in the static HTML, so the scan above
    can't catch a typo in one of these three. Pinned here instead."""
    i18n = _load_i18n_dict()
    assert key in i18n and i18n[key].get("me") and i18n[key].get("en")
